CREATE DATABASE acoustibook
USE acoustibook;


CREATE TABLE Prenotazione (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Data_Inizio DATETIME NOT NULL,
    Data_Fine DATETIME NOT NULL,
    ID_Strumento INT NOT NULL,
    ID_Utente INT NOT NULL,
    ID_Luogo INT NOT NULL,
    FOREIGN KEY (ID_Strumento) REFERENCES Strumento(ID),
    FOREIGN KEY (ID_Utente) REFERENCES Utente(ID),
    FOREIGN KEY (ID_Luogo) REFERENCES Luogo(ID)
);

CREATE TABLE Utente (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Cognome VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Strumento (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Descrizione TEXT
);


CREATE TABLE Luogo (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Descrizione TEXT,
    Indirizzo VARCHAR(255),
    ID_Citta INT NOT NULL,
    FOREIGN KEY (ID_Citta) REFERENCES Citta(ID)
);


CREATE TABLE Citta (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    CAP VARCHAR(10) NOT NULL
);
